
# A string used to distinguish different Supabase projects on the same host. Defaults to the project ID.
project_id = "qxaajirrqrcnmvtowjbg"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "extensions"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328

[auth]
enabled = true
port = 54330
# allowlist of URLs that auth providers are permitted to redirect to post authentication
redirect_urls = ["https://localhost:3000", "https://lovable.dev", "https://preview--qxaajirrqrcnmvtowjbg.lovable.dev"]
# Supabase test JWT 
additional_redirect_urls = ["https://preview--qxaajirrqrcnmvtowjbg.lovable.dev"]

[analytics]
enabled = false
port = 54331
vector_port = 54332

[experimental]
minimal_apis = true

# Configure Edge Functions
[functions]
enabled = true
port = 54333

[functions.a]
verify_jwt = true
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]

[functions.ai-coach]
verify_jwt = false
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
# DEPLOYMENT VERSION: 2.2.0 - Force fresh deployment (2025-10-06)

[functions.blueprint-calculator]
verify_jwt = false
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
[functions.blueprint-calculator.env]
WASM_SOURCE = "full_fallback_chain"
WASM_BUCKET = "astro-wasm"
WASM_OBJECT_PATH = "/astro.wasm"

[functions.blueprint-calculator.check-wasm]
verify_jwt = false
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]

[functions.conversational-assessment]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-intelligent-conversation]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-authentic-insights]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-autonomous-text]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-response-analysis]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.generate-personality-report]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.openai-embeddings]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.unified-brain-processor]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.companion-oracle-conversation]
verify_jwt = false
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.identity-constructs-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.behavioral-triggers-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.execution-bias-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.internal-conflicts-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.spiritual-dimension-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.adaptive-feedback-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.temporal-biology-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.metacognitive-biases-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.attachment-style-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.goal-archetypes-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.crisis-handling-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.identity-flexibility-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.linguistic-fingerprint-analyst]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hermetic-job-creator]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hermetic-background-orchestrator]
verify_jwt = false
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.openai-agent]
verify_jwt = false
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.xp-award-service]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-coach-conversation]
verify_jwt = false
cors = ["*"]
methods = ["POST", "OPTIONS"]

[analytics]
enabled = false
