project_id = "qxaajirrqrcnmvtowjbg"

[api]
port = 54321
schemas = ["public", "storage", "extensions"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328

[auth]
enabled = true
port = 54330
redirect_urls = ["https://localhost:3000", "https://lovable.dev", "https://preview--qxaajirrqrcnmvtowjbg.lovable.dev"]
additional_redirect_urls = ["https://preview--qxaajirrqrcnmvtowjbg.lovable.dev"]

[analytics]
enabled = false
port = 54331
vector_port = 54332

[experimental]
minimal_apis = true

[functions]
enabled = true
port = 54333

[functions.a]
verify_jwt = true
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]

[functions.ai-coach]
verify_jwt = false
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]

[functions.blueprint-calculator]
verify_jwt = false
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
[functions.blueprint-calculator.env]
WASM_SOURCE = "full_fallback_chain"
WASM_BUCKET = "astro-wasm"
WASM_OBJECT_PATH = "/astro.wasm"

[functions.blueprint-calculator.check-wasm]
verify_jwt = false
cors = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]

[functions.conversational-assessment]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-intelligent-conversation]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-authentic-insights]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-autonomous-text]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-response-analysis]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-coach-conversation]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-growth-conversation]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-blend-conversation]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.hacs-dream-conversation]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.generate-personality-report]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.openai-embeddings]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]

[functions.unified-brain-processor]
verify_jwt = true
cors = ["*"]
methods = ["POST", "OPTIONS"]