import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Authentication
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome Back',
    'auth.startJourney': 'Start your journey of self-discovery',
    'auth.continueJourney': 'Sign in to continue your journey',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.alreadyHaveAccount': 'Already have an account? Sign in',
    'auth.needAccount': 'Need an account? Sign up',
    'auth.passwordsDontMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters long',
    'auth.signUpSuccess': 'Check your email for the confirmation link, then you\'ll be redirected to create your Soul Blueprint.',
    'auth.welcomeBackMessage': 'You have been signed in successfully.',
    'auth.signUpFailed': 'Failed to create account',
    'auth.signInFailed': 'Failed to sign in',
    'auth.success': 'Success!',
    
    // Navigation
    'nav.home': 'Home',
    'nav.blueprint': 'Blueprint',
    'nav.coach': 'Coach',
    'nav.tasks': 'Tasks',
    'nav.profile': 'Profile',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    
    // Blueprint Page
    'blueprint.title': 'Soul Blueprint',
    'blueprint.signInRequired': 'You need to sign in to view and edit your Soul Blueprint',
    'blueprint.loading': 'Loading your Soul Blueprint...',
    'blueprint.viewTab': 'View Blueprint',
    'blueprint.editTab': 'Edit Blueprint',
    'blueprint.generatingTab': 'Generating',
    'blueprint.regenerate': 'Regenerate Blueprint',
    'blueprint.chatWithCoach': 'Chat with Soul Coach',
    'blueprint.generating': 'Generating...',
    'blueprint.calculatedUsing': 'Calculated using',
    'blueprint.templateData': 'Using template data',
    'blueprint.welcome': 'Welcome to SoulSync!',
    'blueprint.onboardingMessage': "Let's create your Soul Blueprint through our onboarding process.",
    'blueprint.saved': 'Blueprint saved',
    'blueprint.savedDescription': 'Your Soul Blueprint has been successfully updated',
    'blueprint.errorSaving': 'Error saving blueprint',
    'blueprint.errorLoading': 'Error loading blueprint',
    'blueprint.regenerating': 'Regenerating Blueprint',
    'blueprint.regeneratingDescription': "We're calculating your cosmic profile. This may take a moment...",
    'blueprint.generated': 'Blueprint generated',
    'blueprint.generatedDescription': 'Your Soul Blueprint has been successfully regenerated and saved',
    'blueprint.errorGenerating': 'Error saving generated blueprint',
    'blueprint.realCalculations': '✅ Real Calculations',
    'blueprint.partialData': '⚠️ Partial Data',
    'blueprint.templateDataBadge': '📋 Template Data',
    'blueprint.healthCheckTab': 'Health Check',
    'blueprint.healthCheckShort': 'Health',
    'blueprint.viewer.heading': 'Soul Blueprint for {{name}}',
    'blueprint.viewer.calculatedOn': 'Calculated on {{date}} using {{engine}}',
    'blueprint.viewer.engine.swiss': 'Swiss Ephemeris via Vercel API',
    'blueprint.viewer.engine.vercel': 'Vercel Ephemeris API',
    'blueprint.viewer.engine.default': 'Accurate Astronomical Calculations',
    'blueprint.viewer.usingTemplate': 'Using default template data',
    'blueprint.viewer.getReadingTitle': 'Get Your Complete Reading',
    'blueprint.viewer.getReadingDesc': 'Generate a comprehensive AI analysis that weaves together all aspects of your blueprint',
    'blueprint.viewer.viewFullReading': 'View Full Reading',
    'blueprint.viewer.overview': 'Overview',
    'blueprint.viewer.mbti': 'MBTI',
    'blueprint.viewer.humanDesign': 'Human Design',
    'blueprint.viewer.numerology': 'Numerology',
    'blueprint.viewer.astrology': 'Astrology',
    'blueprint.viewer.overviewDesc': 'A summary of your Soul Blueprint.',
    'blueprint.viewer.welcome': 'Welcome to your Soul Blueprint, {{name}}!',
    'blueprint.viewer.accurateCalculationsShort': '✅ Accurate Calculations',
    'blueprint.viewer.accurateCalculations': 'Your blueprint was generated using precise astronomical calculations from the Swiss Ephemeris, taking into account your exact birth time, location, and historical timezone data.',
    'blueprint.viewer.templateDataShort': '📋 Template Data',
    'blueprint.viewer.templateDataDesc': 'This blueprint uses template data. For accurate calculations based on your birth details, please regenerate your blueprint.',
    'blueprint.viewer.sunSign': 'Sun Sign',
    'blueprint.viewer.moonSign': 'Moon Sign',
    'blueprint.viewer.risingSign': 'Rising Sign',
    'blueprint.viewer.mbtiType': 'MBTI Type',
    'blueprint.viewer.lifePath': 'Life Path',
    'blueprint.viewer.mbtiProfile': 'MBTI Profile',
    'blueprint.viewer.mbtiDesc': 'Your cognitive personality type',
    'blueprint.viewer.coreKeywords': 'Core Keywords',
    'blueprint.viewer.dominantFunction': 'Dominant Function',
    'blueprint.viewer.auxiliaryFunction': 'Auxiliary Function',
    'blueprint.viewer.selfAssessment': 'Self-assessment confidence',
    'blueprint.viewer.humanDesignDesc': 'Your energy type and strategy',
    'blueprint.viewer.hdType': 'Type',
    'blueprint.viewer.profile': 'Profile',
    'blueprint.viewer.authority': 'Authority',
    'blueprint.viewer.strategy': 'Strategy',
    'blueprint.viewer.numerologyProfile': 'Numerology Profile',
    'blueprint.viewer.lifePathNumber': 'Life Path Number',
    'blueprint.viewer.expressionNumber': 'Expression Number',
    'blueprint.viewer.personalityNumber': 'Personality Number',
    'blueprint.viewer.soulUrgeNumber': 'Soul Urge Number',
    'blueprint.viewer.birthdayNumber': 'Birthday Number',
    'blueprint.viewer.lifePurpose': "Your life's purpose and journey",
    'blueprint.viewer.talent': "Your natural talents and abilities",
    'blueprint.viewer.keyAspect': "Key aspect of your persona",
    'blueprint.viewer.innerDesires': "Your inner desires and motivations",
    'blueprint.viewer.birthdayTalent': "Special talents from your birth day",
    'blueprint.viewer.astrologyDesc': 'Your astrological profile',
    'unknown': 'Unknown',
    
    // Blueprint Sections
    'blueprint.overview': 'Overview',
    'blueprint.mbti': 'MBTI',
    'blueprint.humanDesign': 'Human Design',
    'blueprint.bashar': 'Bashar Suite',
    'blueprint.numerology': 'Numerology',
    'blueprint.western': 'Western Astrology',
    'blueprint.chinese': 'Chinese Astrology',
    'blueprint.energyIdentity': 'Energy & Identity',
    'blueprint.westernAstrology': 'Western Astrology',
    'blueprint.chineseAstrology': 'Chinese Astrology',
    'blueprint.novice': 'Novice',
    'blueprint.amateur': 'Amateur',
    'blueprint.pro': 'Pro',
    
    // Coach Page
    'coach.title': 'Soul AI',
    'coach.signInRequired': 'You need to sign in to access your personalized AI guidance',
    'coach.soulCoach': 'Soul Coach',
    'coach.soulGuide': 'Soul Guide',
    'coach.soulCompanion': 'Soul Companion',
    'coach.newConversation': 'New Conversation',
    'coach.blueprintSettings': 'Blueprint Settings',
    
    // Agent Selector
    'agent.chooseStyle': 'Choose Your Guidance Style',
    'agent.separatedDomains': 'Separated domains or integrated approach',
    'agent.separated': 'SEPARATED',
    'agent.integrated': 'INTEGRATED',
    'agent.or': 'OR',
    
    // Agent Descriptions
    'agent.coach.name': 'Soul Coach',
    'agent.coach.description': 'Pure productivity focus',
    'agent.coach.details': 'Goals • Tasks • Achievement',
    'agent.guide.name': 'Soul Guide',
    'agent.guide.description': 'Pure personal growth',
    'agent.guide.details': 'Wisdom • Growth • Meaning',
    'agent.blend.name': 'Soul Companion',
    'agent.blend.description': 'Integrated life guidance',
    'agent.blend.details': 'Seamless • Holistic • Unified',
    
    // Coach Interface
    'coach.todaysProgress': "Today's Progress",
    'coach.dayStreak': '{{count}} day streak',
    'coach.dailyGoals': 'Daily goals',
    'coach.complete': '{{completed}}/{{total}} complete',
    'coach.ready': 'Your Soul Coach is ready',
    'coach.readyDescription': "Let's turn your goals into actionable steps. What would you like to achieve?",
    'coach.quickStart': 'Quick Start:',
    'coach.analyzing': 'Analyzing your goals...',
    'coach.inputPlaceholder': "What's your next goal or challenge?",
    'coach.poweredBy': 'Goal-focused coaching powered by your Soul Blueprint',
    'coach.done': 'Done',
    'coach.schedule': 'Schedule',
    
    // Quick Actions
    'quickAction.breakDownGoal': 'Help me break down my goal',
    'quickAction.createRoutine': 'Create a daily routine',
    'quickAction.setupAccountability': 'Set up accountability check-ins',
    'quickAction.planWeek': 'Plan my week',
    
    // Guide Interface
    'guide.innerCompass': 'Inner Compass',
    'guide.reflectionMode': 'Reflection mode',
    'guide.checkIn': 'Check-in',
    'guide.reflect': 'Reflect',
    'guide.journal': 'Journal',
    'guide.description': 'Your Soul Guide is here to help you understand yourself more deeply and navigate life\'s complexities with wisdom.',
    'guide.awaits': 'Your Soul Guide awaits',
    'guide.awaitsDescription': 'Share what\'s on your heart and mind. Let\'s explore the deeper patterns together.',
    'guide.reflecting': 'Reflecting on your soul\'s wisdom...',
    'guide.inputPlaceholder': "What's stirring in your soul today?",
    'guide.poweredBy': 'Compassionate guidance powered by your Soul Blueprint',
    'guide.exploreDeeper': 'Explore deeper',
    'guide.blueprintLink': 'Blueprint link',
    'guide.tellMore': 'Tell me more about this',
    'guide.howConnect': 'How does this connect to my blueprint?',
    
    // Blend Interface
    'blend.soulCompanion': 'Soul Companion',
    'blend.balancedGuidance': 'Balanced guidance',
    'blend.description': 'Your companion for both achieving goals and understanding yourself deeply',
    'blend.awaits': 'Your Soul Companion awaits',
    'blend.awaitsDescription': 'Ask about productivity, goals, personal growth, or reflection. I\'ll help you find the perfect balance.',
    'blend.finding': 'Finding the perfect balance for you...',
    'blend.inputPlaceholder': 'Ask about goals, growth, or anything on your mind...',
    'blend.poweredBy': 'Balanced guidance combining productivity and personal insight',
    'blend.makeActionable': 'Make actionable',
    'blend.goDeeper': 'Go deeper',
    'blend.blueprintWisdom': 'Blueprint wisdom',
    'blend.setGoal': 'Set a goal',
    'blend.reflectToday': 'Reflect on today',
    'blend.findBalance': 'Find balance',
    'blend.breakThrough': 'Break through blocks',
    
    // Action Messages
    'action.setGoalMessage': 'Help me set and track a meaningful goal',
    'action.reflectMessage': 'I want to reflect on my day and understand my feelings',
    'action.balanceMessage': 'Help me find balance between my productivity and personal growth',
    'action.stuckMessage': "I'm feeling stuck and need help moving forward",
    'action.actionableSteps': 'How can I turn this into actionable steps?',
    'action.deeperMeaning': 'Help me understand the deeper meaning here',
    'action.blueprintSays': 'What would my blueprint say about this?',
    
    // General
    'you': 'You',
    'insight': 'Insight',
    'balanced': 'Balanced',
    'newConversationStarted': 'Started a fresh conversation with your {{agent}}',
    'loading': 'Loading...',
    'error': 'Error',
    'retry': 'Retry',
    'cancel': 'Cancel',
    'save': 'Save',
    'close': 'Close',
    'next': 'Next',
    'previous': 'Previous',
    'continue': 'Continue',
    'send': 'Send',
    
    // Tasks Page
    'tasks.title': 'Aligned Tasks',
    'tasks.subtitle': 'Tasks personalized to your Soul Blueprint',
    'tasks.addPlaceholder': 'Add a new aligned task...',
    'tasks.viewList': 'List',
    'tasks.viewKanban': 'Kanban',
    'tasks.tabAll': 'All',
    'tasks.tabActive': 'Active',
    'tasks.tabCompleted': 'Completed',
    'tasks.noTasks': 'No tasks found',
    'tasks.noActiveTasks': 'No active tasks found',
    'tasks.noCompletedTasks': 'No completed tasks found',
    'tasks.statusTodo': 'To Do',
    'tasks.statusInProgress': 'In Progress',
    'tasks.statusStuck': 'Stuck',
    'tasks.statusCompleted': 'Completed',
    'tasks.priorityLow': 'low',
    'tasks.priorityMedium': 'medium',
    'tasks.priorityHigh': 'high',
    'tasks.dueToday': 'Today',
    'tasks.dueTomorrow': 'Tomorrow',
    'tasks.addedToast': 'Task added',
    'tasks.addedDescription': 'Your new aligned task has been created.',
    'tasks.completedToast': 'Task completed',
    'tasks.completedDescription': 'Great job completing this task!',
    'tasks.reopenedToast': 'Task reopened',
    'tasks.reopenedDescription': "You've reopened this task",
    'tasks.deletedToast': 'Task deleted',
    'tasks.deletedDescription': 'Your task has been removed.',
    'tasks.stuckHelp': 'I notice you have a stuck task. Would you like some help or suggestions to move it forward?',
    
    // Productivity Suite
    'productivity.title': 'Productivity Suite',
    'productivity.subtitle': 'Productivity Suite: Tailored to your unique Soul Blueprint',
    'productivity.focusTimer': 'Focus Timer',
    'productivity.habits': 'Habits',
    'productivity.goals': 'Goals',
    'productivity.planning': 'Planning',
    'productivity.loading': 'Loading your personalized focus timer...',
    'productivity.description1': 'Focus timer adjusts to your cognitive patterns',
    'productivity.description2': 'Habits aligned with your energy cycles',
    'productivity.description3': 'Goals framed around your natural strengths',
    
    // Menu Options
    'menu.status': 'Status',
    'menu.delete': 'Delete',
    
    // Pomodoro Timer
    'pomodoro.breakTime': 'Break Time',
    'pomodoro.focusTimer': 'Focus Timer',
    'pomodoro.pomodorosCompleted': 'Pomodoros completed today',
    'pomodoro.standardRhythm': 'Standard 25/5 Pomodoro rhythm',
    'pomodoro.deepFocusRhythm': 'Extended focus for deep work (40/5)',
    'pomodoro.quickBurstsRhythm': 'Quick bursts for enhanced attention (15/5)',
    'pomodoro.breakFinished': 'Break finished!',
    'pomodoro.timeToFocus': 'Time to focus on your task.',
    'pomodoro.pomodoroCompleted': 'Pomodoro completed!',
    'pomodoro.takeBreak': 'Take a short break.',
    
    // Habit Tracker
    'habits.title': 'Habit Tracker',
    'habits.addPlaceholder': 'Add a new habit...',
    'habits.noHabits': 'No habits added yet. Add one to get started!',
    'habits.alignedWithBlueprint': 'Aligned with your blueprint',
    'habits.created': 'Habit created',
    'habits.createdDescription': '{{name}} added to your habit tracker.',
    'habits.suggestedAdded': 'Suggested habit added',
    'habits.suggestedAddedDescription': '{{name}} added to your habit tracker.',
    'habits.deleted': 'Habit deleted',
    'habits.deletedDescription': 'The habit has been removed from your tracker.',
    'habits.daysSingular': 'day',
    'habits.daysPlural': 'days',
    
    // Goal Setting
    'goals.smartGoals': 'SMART Goals',
    'goals.addGoal': 'Add Goal',
    'goals.cancel': 'Cancel',
    'goals.goalTitle': 'Goal Title',
    'goals.goalTitlePlaceholder': 'What do you want to achieve?',
    'goals.description': 'Description',
    'goals.descriptionPlaceholder': 'Be specific about what success looks like',
    'goals.category': 'Category',
    'goals.selectCategory': 'Select a category',
    'goals.targetDate': 'Target Date',
    'goals.milestones': 'Milestones',
    'goals.addMilestone': 'Add a milestone',
    'goals.createGoal': 'Create Goal',
    'goals.noGoals': 'No goals added yet. Add your first SMART goal to get started!',
    'goals.progress': 'Progress',
    'goals.milestonesTitle': 'Milestones',
    'goals.noMilestones': 'No milestones added yet.',
    'goals.noDeadline': 'No deadline',
    'goals.created': 'Goal created',
    'goals.createdDescription': 'New SMART goal has been added.',
    'goals.deleted': 'Goal deleted',
    'goals.deletedDescription': 'The goal has been removed.',
    
    // Goal Categories
    'goals.categoryPersonal': 'Personal Growth',
    'goals.categoryCareer': 'Career & Work',
    'goals.categoryHealth': 'Health & Wellness',
    'goals.categoryRelationships': 'Relationships',
    'goals.categorySpiritual': 'Spiritual Growth',
    'goals.categoryFinancial': 'Financial',
    'goals.categoryCreative': 'Creative Projects',
    
    // Profile Page
    'profile.stats': 'Stats',
    'profile.goals': 'Goals', 
    'profile.settings': 'Settings',
    'profile.growthJourney': 'Your Growth Journey',
    'profile.blueprintCompletion': 'Blueprint Completion',
    'profile.activeGoals': 'Active Goals',
    'profile.tasksCompleted': 'Tasks Completed',
    'profile.coachConversations': 'Coach Conversations',
    'profile.weeklyInsights': 'Weekly Insights',
    'profile.mostProductiveDay': 'Most Productive Day',
    'profile.energyPeaks': 'Energy Peaks',
    'profile.focusSessions': 'Focus Sessions',
    'profile.thisWeek': 'this week',
    'profile.aligned': 'Aligned',
    'profile.wednesday': 'Wednesday',
    'profile.morningPeaks': 'Morning: 9-11am',
    'profile.noGoals': 'No goals found',
    'profile.createFirstGoal': 'Start by creating your first goal to track your progress',
    'profile.viewAllGoals': 'View All Goals',
    'profile.appSettings': 'App Settings',
    'profile.notifications': 'Notifications',
    'profile.darkMode': 'Dark Mode',
    'profile.accountSettings': 'Account Settings',
    'profile.accountSettingsTooltip': 'Configure your account preferences',
    'profile.logoutSuccess': 'You have been successfully logged out.',
    'profile.logoutError': 'Failed to log out. Please try again.',
    'profile.darkModeEnabled': 'Dark mode enabled',
    'profile.lightModeEnabled': 'Light mode enabled',
    'profile.darkModeDescription': 'Switched to dark theme',
    'profile.lightModeDescription': 'Switched to light theme',
    'profile.taskCompleted': 'Task completed!',
    'profile.taskCompletedDescription': 'Great job on completing your task.',
    'profile.errorLoading': 'Error loading profile',
    'profile.progress': 'Progress',
    'profile.complete': 'Complete',
    'profile.onTrack': 'On track',
    'profile.status.completed': 'Completed',
    'profile.status.paused': 'Paused',
    'profile.status.active': 'Active',
    'profile.focusMode': 'Focus Mode',
    
    // Index page/homepage
    'index.welcome': 'Welcome to <span class="gradient-text">Soul Sync</span>',
    'index.subtitle': 'Live by Design, Understand Yourself and Achieve Through Alignment!',
    'index.dreams': 'Dreams',
    'index.dreamsDesc': 'Journey to Success',
    'index.growth': 'Growth',
    'index.growthDesc': 'Inner Wisdom',
    'index.companion': 'Companion',
    'index.companionDesc': 'AI Guide',
    'index.demo': 'See How Personalization Works',
    'index.startJourney': 'Start Your Journey',
    'index.getStarted': 'Get Started',
    'index.chatWithCompanion': 'Chat with Soul Companion',
    'index.signIn': 'Sign In',
    'index.welcomeBackReady': 'Welcome back! Your Soul Blueprint is ready to explore.',
    'index.createToGetStarted': "Welcome! Let's create your Soul Blueprint to get started.",
    'index.readyExplore': 'Your Soul Blueprint is ready! Explore the features below.',
    'index.profileFeature': 'Profile',
    'index.backToHome': '← Back to Home',
    
    // Dreams Page (NEW KEYS for /dreams)
    "dreams.title": "Dreams & Goals",
    "dreams.description": "Transform your biggest dreams into achievable milestones with AI-powered guidance",
    "dreams.getStarted": "Get Started",
    "dreams.whatsYourDream": "What's Your Dream?",
    "dreams.heroDescription": "Turn your biggest aspiration into a personalized, step-by-step journey",
    "dreams.whyImportant": "Why is this important?",
    "dreams.placeholderDream": "Launch my creative business, get fit...",
    "dreams.placeholderWhy": "Share what drives this dream...",
    "dreams.category": "Category",
    "dreams.timeline": "Timeline",
    "dreams.tabs.journey": "Journey",
    "dreams.tabs.tasks": "Tasks",
    "dreams.tabs.focus": "Focus",
    "dreams.tabs.habits": "Habits",
    "dreams.tab.journeyMap": "Journey Map",
    "dreams.tab.yourTasks": "Your Tasks",
    "dreams.tab.focusSession": "Focus Session",
    "dreams.tab.habits": "Daily Habits",
    "dreams.aiInsighLabel": "Or explore other ways to start",
    "dreams.aiButtonTitle": "Talk with AI Dream Coach",
    "dreams.aiButtonDesc": "Explore dreams through conversation",
    "dreams.journeyButtonTitle": "View Current Journey",
    "dreams.journeyButtonDesc": "Continue your dream progress",
    "dreams.createJourney": "Create My Dream Journey",
    "dreams.creatingJourney": "Creating Your AI Journey...",
    "dreams.newDream": "New Dream",
    "dreams.new": "New",
    "dreams.yourJourney": "Your Journey",
    "dreams.trackProgress": "Track progress & stay focused",
    "dreams.journeyMap": "Journey Map",
    "dreams.continue": "Continue",
    "dreams.taskCompletedTitle": "🎉 Task Completed!",
    "dreams.taskCompletedDesc": "Great work! The task has been marked as complete.",
    "dreams.dreamRequired": "Dream Required",
    "dreams.dreamRequiredDesc": "Please enter your dream or goal",

    // --- Growth/SpiritualGrowth Page ---
    'growth.title': 'Growth Mode',
    'growth.positionLabel': 'Position:',
    'growth.conversationMessages': 'conversation messages',
    'growth.headerSubtitle': 'Inner reflection & soul wisdom',
    'growth.exploringArea': 'Exploring {{area}}',
    'growth.chooseYourTool': 'Choose Your Growth Tool',
    'growth.chooseYourToolDescription': 'Start with Soul Guide for a personalized journey, or select any tool above',
    'growth.tools.soulGuide': 'Soul Guide',
    'growth.tools.moodTracker': 'Mood Tracker',
    'growth.tools.reflectionPrompts': 'Reflection Prompts',
    'growth.tools.insightJournal': 'Insight Journal',
    'growth.tools.weeklyInsights': 'Weekly Insights',
    'growth.tools.freeChat': 'Free Chat',
    'growth.startSoulCheckIn': 'Start Soul Check-in',
  },
  nl: {
    // Authentication
    'auth.createAccount': 'Account Aanmaken',
    'auth.welcomeBack': 'Welkom Terug',
    'auth.startJourney': 'Begin je reis van zelfontdekking',
    'auth.continueJourney': 'Log in om je reis voort te zetten',
    'auth.email': 'Email',
    'auth.password': 'Wachtwoord',
    'auth.confirmPassword': 'Bevestig Wachtwoord',
    'auth.enterEmail': 'Voer je email in',
    'auth.enterPassword': 'Voer je wachtwoord in',
    'auth.confirmPasswordPlaceholder': 'Bevestig je wachtwoord',
    'auth.alreadyHaveAccount': 'Heb je al een account? Log in',
    'auth.needAccount': 'Heb je een account nodig? Registreer',
    'auth.passwordsDontMatch': 'Wachtwoorden komen niet overeen',
    'auth.passwordTooShort': 'Wachtwoord moet minimaal 6 tekens lang zijn',
    'auth.signUpSuccess': 'Controleer je email voor de bevestigingslink, dan word je doorgestuurd om je Ziel Blauwdruk te maken.',
    'auth.welcomeBackMessage': 'Je bent succesvol ingelogd.',
    'auth.signUpFailed': 'Aanmaken account mislukt',
    'auth.signInFailed': 'Inloggen mislukt',
    'auth.success': 'Succes!',
    
    // Navigation
    'nav.home': 'Home',
    'nav.blueprint': 'Blauwdruk',
    'nav.coach': 'Coach',
    'nav.tasks': 'Taken',
    'nav.profile': 'Profiel',
    'nav.signIn': 'Inloggen',
    'nav.signOut': 'Uitloggen',
    
    // Blueprint Page
    'blueprint.title': 'Ziel Blauwdruk',
    'blueprint.signInRequired': 'Je moet inloggen om je Ziel Blauwdruk te bekijken en bewerken',
    'blueprint.loading': 'Je Ziel Blauwdruk laden...',
    'blueprint.viewTab': 'Blauwdruk Bekijken',
    'blueprint.editTab': 'Blauwdruk Bewerken',
    'blueprint.generatingTab': 'Genereren',
    'blueprint.regenerate': 'Blauwdruk Regenereren',
    'blueprint.chatWithCoach': 'Chat met Ziel Coach',
    'blueprint.generating': 'Genereren...',
    'blueprint.calculatedUsing': 'Berekend met',
    'blueprint.templateData': 'Gebruikt sjabloongegevens',
    'blueprint.welcome': 'Welkom bij SoulSync!',
    'blueprint.onboardingMessage': 'Laten we je Ziel Blauwdruk maken via ons onboarding proces.',
    'blueprint.saved': 'Blauwdruk opgeslagen',
    'blueprint.savedDescription': 'Je Ziel Blauwdruk is succesvol bijgewerkt',
    'blueprint.errorSaving': 'Fout bij opslaan blauwdruk',
    'blueprint.errorLoading': 'Fout bij laden blauwdruk',
    'blueprint.regenerating': 'Blauwdruk Regenereren',
    'blueprint.regeneratingDescription': 'We berekenen je kosmische profiel. Dit kan even duren...',
    'blueprint.generated': 'Blauwdruk gegenereerd',
    'blueprint.generatedDescription': 'Je Ziel Blauwdruk is succesvol geregenereerd en opgeslagen',
    'blueprint.errorGenerating': 'Fout bij opslaan gegenereerde blauwdruk',
    'blueprint.realCalculations': '✅ Echte Berekeningen',
    'blueprint.partialData': '⚠️ Gedeeltelijke Gegevens',
    'blueprint.templateDataBadge': '📋 Sjabloon Gegevens',
    'blueprint.healthCheckTab': 'Gezondheidscheck',
    'blueprint.healthCheckShort': 'Gezondheid',
    'blueprint.viewer.heading': 'Ziel Blauwdruk voor {{name}}',
    'blueprint.viewer.calculatedOn': 'Berekend op {{date}} met {{engine}}',
    'blueprint.viewer.engine.swiss': 'Swiss Ephemeris via Vercel API',
    'blueprint.viewer.engine.vercel': 'Vercel Ephemeris API',
    'blueprint.viewer.engine.default': 'Nauwkeurige astronomische berekeningen',
    'blueprint.viewer.usingTemplate': 'Gebruikt standaard sjabloongegevens',
    'blueprint.viewer.getReadingTitle': 'Ontvang je volledige reading',
    'blueprint.viewer.getReadingDesc': 'Genereer een uitgebreide AI-analyse die alle aspecten van je blauwdruk samenbrengt',
    'blueprint.viewer.viewFullReading': 'Toon volledige reading',
    'blueprint.viewer.overview': 'Overzicht',
    'blueprint.viewer.mbti': 'MBTI',
    'blueprint.viewer.humanDesign': 'Human Design',
    'blueprint.viewer.numerology': 'Numerologie',
    'blueprint.viewer.astrology': 'Astrologie',
    'blueprint.viewer.overviewDesc': 'Een samenvatting van je Ziel Blauwdruk.',
    'blueprint.viewer.welcome': 'Welkom bij je Ziel Blauwdruk, {{name}}!',
    'blueprint.viewer.accurateCalculationsShort': '✅ Nauwkeurige Berekeningen',
    'blueprint.viewer.accurateCalculations': 'Je blauwdruk is gegenereerd met nauwkeurige astronomische berekeningen van de Swiss Ephemeris, op basis van je exacte geboortetijd, locatie en historische tijdzonegegevens.',
    'blueprint.viewer.templateDataShort': '📋 Sjabloon Gegevens',
    'blueprint.viewer.templateDataDesc': 'Deze blauwdruk gebruikt sjabloongegevens. Voor nauwkeurige berekeningen op basis van je geboortedetails, regenereer je blauwdruk.',
    'blueprint.viewer.sunSign': 'Zonneteken',
    'blueprint.viewer.moonSign': 'Maanteken',
    'blueprint.viewer.risingSign': 'Rijzende teken',
    'blueprint.viewer.mbtiType': 'MBTI Type',
    'blueprint.viewer.lifePath': 'Levenspad',
    'blueprint.viewer.mbtiProfile': 'MBTI Profiel',
    'blueprint.viewer.mbtiDesc': 'Je cognitieve persoonlijkheidstype',
    'blueprint.viewer.coreKeywords': 'Kernwoorden',
    'blueprint.viewer.dominantFunction': 'Dominante Functie',
    'blueprint.viewer.auxiliaryFunction': 'Hulpfunctie',
    'blueprint.viewer.selfAssessment': 'Zelfinschatting zekerheid',
    'blueprint.viewer.humanDesignDesc': 'Je energietype en strategie',
    'blueprint.viewer.hdType': 'Type',
    'blueprint.viewer.profile': 'Profiel',
    'blueprint.viewer.authority': 'Autoriteit',
    'blueprint.viewer.strategy': 'Strategie',
    'blueprint.viewer.numerologyProfile': 'Numerologie Profiel',
    'blueprint.viewer.lifePathNumber': 'Levenspadnummer',
    'blueprint.viewer.expressionNumber': 'Expressienummer',
    'blueprint.viewer.personalityNumber': 'Persoonlijkheidsnummer',
    'blueprint.viewer.soulUrgeNumber': 'Zielverlangen Nummer',
    'blueprint.viewer.birthdayNumber': 'Geboortedag Nummer',
    'blueprint.viewer.lifePurpose': 'Je levensdoel en reis',
    'blueprint.viewer.talent': 'Je natuurlijke talenten en vaardigheden',
    'blueprint.viewer.keyAspect': 'Belangrijk aspect van je persona',
    'blueprint.viewer.innerDesires': 'Je innerlijke verlangens en motivaties',
    'blueprint.viewer.birthdayTalent': 'Speciale talenten van je geboortedag',
    'blueprint.viewer.astrologyDesc': 'Je astrologisch profiel',
    'unknown': 'Onbekend',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{{${param}}}`, value);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageProvider;
