import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Common
    you: 'You',
    streaming: 'Streaming',
    insight: 'Insight',
    save: 'Save',
    back: 'Back',
    continue: 'Continue',
    error: 'Error',
    
    // Navigation
    'nav.home': 'Home',
    'nav.growth': 'Growth',
    'nav.coach': 'Coach',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    
    // Language
    'language.english': 'English',
    'language.dutch': 'Dutch',
    
    // Auth
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.createAccount': 'Create Account',
    'auth.welcomeBack': 'Welcome Back',
    'auth.startJourney': 'Start your soul journey today',
    'auth.continueJourney': 'Continue your journey of self-discovery',
    'auth.alreadyHaveAccount': 'Already have an account? Sign in',
    'auth.needAccount': 'Need an account? Sign up',
    'auth.signUpSuccess': 'Account created! Please check your email to verify your account.',
    'auth.welcomeBackMessage': 'Welcome back to your soul journey!',
    'auth.signInFailed': 'Failed to sign in. Please check your credentials.',
    'auth.signUpFailed': 'Failed to create account. Please try again.',
    'auth.passwordsDontMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.success': 'Success',
    'coach.signInRequired': 'Please sign in to access your personal AI coach and growth tools.',
    
    // Coach
    'coach.soulGuide': 'Soul Guide',
    'coach.newConversation': 'New Conversation',
    'newConversationStarted': 'New conversation started with {{agent}}',
    
    // Index/Home Page
    'index.welcome': 'Welcome to Your <br /><span class="text-soul-purple">Soul Journey</span>',
    'index.subtitle': 'Discover your authentic path through personalized AI guidance and spiritual growth tools.',
    'index.dreams': 'Dreams & Goals',
    'index.dreamsDesc': 'Transform dreams into reality',
    'index.growth': 'Spiritual Growth',
    'index.growthDesc': 'Inner wisdom & reflection',
    'index.companion': 'AI Companion',
    'index.companionDesc': 'Personalized guidance & chat',
    'index.demo': 'View Personality Demo',
    'index.startJourney': 'Start Your Journey',
    'index.chatWithCompanion': 'Chat with AI Companion',
    'index.welcomeBackReady': 'Welcome back! Your soul companion is ready to guide you further on your journey.',
    'index.createToGetStarted': 'Welcome! Let\'s create your personal blueprint to get started on your soul journey.',
    'index.readyExplore': 'Perfect! You\'re all set up. Let\'s explore your growth tools and continue your journey.',
    'index.backToHome': 'Back to Home',
    'index.getStarted': 'Get Started',
    'index.signIn': 'Sign In',
    
    // Rotating subtitle messages
    'index.rotatingMessages': [
      'Feeling stuck? SoulSync shows you the next right step.',
      'Lost in the noise? Discover guidance that speaks your truth.',
      'Overthinking your path? Align, act, and breathe again.',
      'When nothing works, your design holds the key.',
      'SoulSync ends the cycle of forcing what doesn\'t fit.',
      'Not lazy. Not broken. Just misaligned.',
      'You\'re not behind — you\'re off-track. SoulSync resets your course.',
      'No more plans that ignore who you are.',
      'Goals aren\'t the problem. Strategy that ignores your soul is.',
      'When burnout wins, SoulSync realigns you with joy. Break down your dream — not your spirit.',
      'Turn chaos into clarity, one soul-aligned task at a time.',
      'Productivity that honors your wiring.',
      'From blueprint to action — one aligned step at a time.',
      'Finally: a task system built for your energy, not against it.',
      'Your goals, your rhythm, your way.',
      'Dream big. Then let SoulSync reverse-engineer your path.',
      'Every task in tune with who you are.',
      'Clarity. Strategy. Action. All from your inner code.',
      'Soul-led productivity — so you can actually follow through. SoulSync helps when you\'re tired of guessing.',
      'When you\'re stuck, it\'s not more willpower you need — it\'s more alignment.',
      'Feel known. Make progress.',
      'Real growth starts with self-understanding.',
      'It\'s not about doing more — it\'s about doing what\'s right for you.'
    ],
    
    // Onboarding
    'onboarding.welcome': 'Welcome to SoulSync',
    'onboarding.welcomeDesc': 'I\'m your personal astrology guide. Let me help you discover your cosmic blueprint.',
    'onboarding.beginJourney': 'Begin My Journey',
    'onboarding.step': 'Step',
    'onboarding.of': 'of',
    'onboarding.whatsYourName': 'What\'s your name?',
    'onboarding.fullName': 'Full Name',
    'onboarding.fullNamePlaceholder': 'Enter your full name',
    'onboarding.preferredName': 'Preferred Name (optional)',
    'onboarding.preferredNamePlaceholder': 'How would you like to be addressed?',
    'onboarding.whenWereBorn': 'When were you born?',
    'onboarding.birthDate': 'Birth Date',
    'onboarding.day': 'Day',
    'onboarding.month': 'Month',
    'onboarding.year': 'Year',
    'onboarding.selectExactDate': 'Select your exact birth date for accurate calculations',
    'onboarding.whatTimeWereBorn': 'What time were you born?',
    'onboarding.birthTime': 'Birth Time (Local Time)',
    'onboarding.birthTimeDesc': 'Enter the local time where you were born - we\'ll automatically handle timezone conversion',
    'onboarding.whereWereBorn': 'Where were you born?',
    'onboarding.birthLocation': 'Birth Location',
    'onboarding.birthLocationPlaceholder': 'City, Country (e.g., Paramaribo, Suriname)',
    'onboarding.birthLocationDesc': 'We\'ll automatically find the exact coordinates and historical timezone',
    'onboarding.tellPersonality': 'Tell us about your personality',
    'onboarding.generatingBlueprint': 'Generating Your Soul Blueprint',
    'onboarding.choosePath': 'Choose Your Path',
    'onboarding.choosePathDesc': 'Let\'s set up your coaching preferences to personalize your experience.',
    'onboarding.authRequired': 'Authentication Required',
    'onboarding.authRequiredDesc': 'Please sign in to generate your Soul Blueprint.',
    'onboarding.devMode': 'Dev Mode: Multiple onboarding attempts supported',
    'onboarding.devModePrefs': 'Dev Mode: Preferences will be stored in goal_stack',
    
    // Blueprint Generation
    'blueprint.generating': 'Generating your Soul Blueprint...',
    'blueprint.connecting': 'Connecting to celestial database...',
    'blueprint.calculating': 'Calculating planetary positions...',
    'blueprint.generatingProfile': 'Generating your unique profile...',
    'blueprint.finalizing': 'Finalizing your Soul Blueprint...',
    'blueprint.complete': 'Blueprint Generation Complete!',
    'blueprint.completeDesc': 'Your Soul Blueprint has been created successfully.',
    'blueprint.error': 'Blueprint Generation Error',
    'blueprint.tryAgain': 'Try Again',
    'blueprint.maxRetries': 'Maximum retry attempts reached. Please check your information and try again later.',
    'blueprint.generated': 'Blueprint Generated Successfully',
    'blueprint.generatedDesc': 'Your soul blueprint has been created and is ready to explore!',
    'blueprint.partial': 'Blueprint Generation Partial',
    'blueprint.partialDesc': 'Some calculations were not fully accurate, but we\'ve created your blueprint with the best available data.',
    'blueprint.saveFailed': 'Your blueprint was generated but couldn\'t be saved. Please try again.',
    'blueprint.unexpectedError': 'There was a problem generating your blueprint. Please try again.',
    'blueprint.tooManyAttempts': 'Too Many Attempts',
    'blueprint.tooManyAttemptsDesc': 'Failed after {{attempts}} attempts. Please check your birth information and try again later.',
    
    // Goal Selection
    'goals.primaryFocus': 'What\'s your primary focus area?',
    'goals.guidanceLevel': 'How much guidance do you prefer?',
    'goals.lightTouch': 'Light touch',
    'goals.structuredGuidance': 'Structured guidance',
    'goals.yourSelections': 'Your Selections:',
    'goals.focus': 'Focus:',
    'goals.guidanceLevelLabel': 'Guidance Level:',
    'goals.completeSetup': 'Complete Setup',
    'goals.saving': 'Saving...',
    'goals.tryAgain': 'Try Again',
    'goals.exploring': 'I\'m still exploring and figuring things out',
    'goals.personalGrowth': 'Personal Growth & Self-Discovery',
    'goals.careerSuccess': 'Career Success & Professional Development',
    'goals.relationships': 'Relationships & Communication',
    'goals.healthWellness': 'Health & Wellness',
    'goals.creativity': 'Creativity & Self-Expression',
    'goals.spiritualDevelopment': 'Spiritual Development',
    'goals.guidance1': 'Minimal guidance - I prefer to explore independently',
    'goals.guidance2': 'Light guidance - Occasional suggestions and insights',
    'goals.guidance3': 'Balanced approach - Regular guidance with flexibility',
    'goals.guidance4': 'Active guidance - Structured support and recommendations',
    'goals.guidance5': 'Maximum guidance - Comprehensive coaching and direction',
    'goals.welcomeComplete': 'Welcome to SoulSync!',
    'goals.welcomeCompleteDesc': 'Your Soul Blueprint is complete. Welcome to your personalized journey.',
    'goals.errorSaving': 'Error Saving Preferences',
    
    // Growth
    'growth.title': 'Growth Mode',
    'growth.headerSubtitle': 'Inner reflection & soul wisdom',
    'growth.positionLabel': 'Position:',
    'growth.conversationMessages': 'conversation messages',
    'growth.chooseYourTool': 'Choose Your Soul Tool',
    'growth.chooseYourToolDescription': 'Select from the tools above to begin your inner journey.',
    'growth.startSoulCheckIn': 'Start Soul Check-in',
    'growth.exploringArea': 'Exploring {{area}}',
    
    // Growth Tools
    'growth.tools.soulGuide': 'Soul Guide',
    'growth.tools.moodTracker': 'Mood Tracker',
    'growth.tools.reflectionPrompts': 'Reflection Prompts',
    'growth.tools.insightJournal': 'Insight Journal',
    'growth.tools.weeklyInsights': 'Weekly Insights',
    'growth.tools.freeChat': 'Free Chat',
    
    // Life Areas
    'lifeArea.selector.title': 'Choose Your Life Area',
    'lifeArea.selector.subtitle': 'Select an area of life to explore and grow',
    'lifeArea.home.name': 'Home',
    'lifeArea.home.description': 'Family, living space, domestic harmony',
    'lifeArea.career.name': 'Career',
    'lifeArea.career.description': 'Purpose, professional growth, impact',
    'lifeArea.finances.name': 'Finances',
    'lifeArea.finances.description': 'Abundance, security, money mindset',
    'lifeArea.relationships.name': 'Relationships',
    'lifeArea.relationships.description': 'Love, friendship, community connection',
    'lifeArea.wellbeing.name': 'Wellbeing',
    'lifeArea.wellbeing.description': 'Health, energy, mental clarity',
    'lifeArea.creativity.name': 'Creativity',
    'lifeArea.creativity.description': 'Artistic expression, innovation, imagination',
    'lifeArea.spirituality.name': 'Spirituality',
    'lifeArea.spirituality.description': 'Soul connection, inner wisdom, sacred practices',
    
    // Dreams
    'dreams.title': 'Dreams & Goals',
    'dreams.description': 'Transform your dreams into achievable journeys with AI-powered guidance.',
    'dreams.getStarted': 'Get Started',
    'dreams.whatsYourDream': 'What\'s Your Dream?',
    'dreams.heroDescription': 'Transform your biggest dreams into a personalized journey with AI-powered milestones and soul-aligned guidance.',
    'dreams.placeholderDream': 'I want to start my own business...',
    'dreams.whyImportant': 'Why is this important to you?',
    'dreams.placeholderWhy': 'This will give me freedom and purpose...',
    'dreams.category': 'Category',
    'dreams.timeline': 'Timeline',
    'dreams.createJourney': 'Create My Journey',
    'dreams.creatingJourney': 'Creating your journey...',
    'dreams.aiInsighLabel': 'Or let AI guide you:',
    'dreams.aiButtonTitle': 'AI-Guided Dream Discovery',
    'dreams.aiButtonDesc': 'Let me help you discover and define your dreams',
    'dreams.journeyButtonTitle': 'View Existing Journey',
    'dreams.journeyButtonDesc': 'Continue your current dream journey',
    'dreams.yourJourney': 'Your Journey',
    'dreams.trackProgress': 'Track your progress and milestones',
    'dreams.newDream': 'New Dream',
    'dreams.new': 'New',
    'dreams.tabs.journey': 'Journey',
    'dreams.tabs.tasks': 'Tasks',
    'dreams.tabs.focus': 'Focus',
    'dreams.tabs.habits': 'Habits',
    'dreams.tab.yourTasks': 'Your Tasks',
    'dreams.tab.focusSession': 'Focus Session',
    'dreams.tab.habits': 'Daily Habits',
    
    // Goals
    'goals.categoryPersonal': 'Personal Growth',
    'goals.categoryCareer': 'Career & Purpose',
    'goals.categoryHealth': 'Health & Wellness',
    'goals.categoryRelationships': 'Relationships',
    'goals.categoryCreative': 'Creativity & Expression',
    'goals.categoryFinancial': 'Financial',
    'goals.categorySpiritual': 'Spiritual',
    'goals.targetDate': 'Target Date',
    
    // Mood Tracker
    'mood.title': 'Daily Mood & Energy Check-in',
    'mood.subtitle': 'Track your emotional patterns and energy levels',
    'mood.currentMood': 'How are you feeling right now?',
    'mood.energyLevel': 'What\'s your energy like?',
    'mood.saveEntry': 'Save Mood Entry',
    'mood.entrySaved': 'Mood entry saved!',
    'mood.entryDescription': 'Your mood patterns help identify emotional trends and triggers.',
    'mood.moods.joyful': 'Joyful',
    'mood.moods.peaceful': 'Peaceful',
    'mood.moods.grateful': 'Grateful',
    'mood.moods.excited': 'Excited',
    'mood.moods.neutral': 'Neutral',
    'mood.moods.tired': 'Tired',
    'mood.moods.anxious': 'Anxious',
    'mood.moods.frustrated': 'Frustrated',
    'mood.moods.sad': 'Sad',
    'mood.energy.high': 'High Energy',
    'mood.energy.steady': 'Steady Energy',
    'mood.energy.low': 'Low Energy',
    'mood.energy.depleted': 'Depleted',
    
    // MoodTracker specific
    'moodTracker.title': 'Daily Mood & Energy Check-in',
    'moodTracker.emotionalState': 'How are you feeling right now?',
    'moodTracker.energyLevel': 'What\'s your energy like?',
    'moodTracker.joyful': 'Joyful',
    'moodTracker.content': 'Content',
    'moodTracker.neutral': 'Neutral',
    'moodTracker.reflective': 'Reflective',
    'moodTracker.challenged': 'Challenged',
    'moodTracker.high': 'High Energy',
    'moodTracker.steady': 'Steady Energy',
    'moodTracker.low': 'Low Energy',
    'moodTracker.moodTracked': 'Mood tracked',
    'moodTracker.moodSaved': 'mood with {{energy}} energy saved',
    'moodTracker.saveToPatterns': 'Save to Patterns',
    'moodTracker.patternsHelp': 'Your mood patterns help identify emotional trends and triggers.',
    
    // Guide Interface
    'guide.innerCompass': 'Inner Compass',
    'guide.reflectionMode': 'Reflection Mode',
    'guide.checkIn': 'Check In',
    'guide.reflect': 'Reflect',
    'guide.journal': 'Journal',
    'guide.description': 'Your personal toolkit for deep soul exploration and authentic growth.',
    'guide.awaits': 'Your Soul Guide Awaits',
    'guide.awaitsDescription': 'Share what\'s in your heart, and let\'s explore your inner wisdom together.',
    'guide.reflecting': 'Reflecting on your soul\'s wisdom...',
    'guide.inputPlaceholder': 'Share what\'s in your heart...',
    'guide.poweredBy': 'Powered by soul wisdom & authentic guidance',
    'guide.exploreDeeper': 'Explore Deeper',
    'guide.blueprintLink': 'Blueprint Link',
    'guide.tellMore': 'Tell me more about this insight and how it connects to my personal growth.',
    'guide.howConnect': 'How does this connect to my blueprint and authentic self?',
    
    // Insight Journal
    'journal.title': 'Soul Insights Journal',
    'journal.placeholder': 'Capture your insights, realizations, or aha moments...',
    'journal.tagLabel': 'Tag this insight:',
    'journal.saveButton': 'Save to Journal',
    'journal.saved': 'Insight saved to your journal!',
    'journal.description': 'Your insights create a personal knowledge base for pattern recognition and growth tracking.',
    'journal.tags.breakthrough': 'Breakthrough',
    'journal.tags.pattern': 'Pattern',
    'journal.tags.gratitude': 'Gratitude',
    'journal.tags.challenge': 'Challenge',
    'journal.tags.growth': 'Growth',
    'journal.tags.clarity': 'Clarity',
    'journal.tags.alignment': 'Alignment',
    'journal.tags.wisdom': 'Wisdom',
    
    // Weekly Insights
    'weekly.title': 'Your Weekly Soul Insights',
    'weekly.growthScore': 'Growth Score',
    'weekly.dominantMood': 'Dominant Mood Pattern',
    'weekly.keyReflections': 'Key Reflection Areas',
    'weekly.growthThemes': 'Growth Themes',
    'weekly.observedPatterns': 'Observed Patterns',
    'weekly.patterns.awareness': 'Self-awareness increasing',
    'weekly.patterns.consistency': 'Consistency building',
    
    // Reflection Prompts
    'reflection.title': 'Reflection & Growth Tracking',
    'reflection.dailyReflection': 'Daily Reflection',
    'reflection.deepInsight': 'Deep Insight',
    'reflection.lifeDirection': 'Life Direction',
    'reflection.saveReflection': 'Save Reflection',
    'reflection.saved': 'Reflection saved to your growth patterns!',
    'reflection.description': 'Your reflections build a personal growth database for weekly insights and pattern recognition.',
    'reflection.placeholder': 'Write your thoughts and insights here...',
    'reflection.reflecting': 'Reflecting on:',
    
    // Daily Reflection Prompts
    'reflection.daily.joy': 'What brought me the most joy today?',
    'reflection.daily.challenge': 'What challenged me and what did I learn?',
    'reflection.daily.authentic': 'How did I honor my authentic self today?',
    'reflection.daily.gratitude': 'What am I grateful for right now?',
    
    // Deep Insight Prompts
    'reflection.insight.pattern': 'What pattern keeps showing up in my life?',
    'reflection.insight.soul': 'What is my soul trying to tell me?',
    'reflection.insight.comfort': 'How am I growing beyond my comfort zone?',
    'reflection.insight.blueprint': 'What does my blueprint reveal about this situation?',
    
    // Life Direction Prompts
    'reflection.direction.aligned': 'What feels most aligned with my purpose?',
    'reflection.direction.resisting': 'Where am I resisting my natural flow?',
    'reflection.direction.trust': 'What would I do if I fully trusted myself?',
    'reflection.direction.energy': 'How can I honor my authentic energy today?',
  },
  nl: {
    // Common
    you: 'Jij',
    streaming: 'Streaming',
    insight: 'Inzicht',
    save: 'Opslaan',
    back: 'Terug',
    continue: 'Doorgaan',
    error: 'Fout',
    
    // Navigation
    'nav.home': 'Home',
    'nav.growth': 'Groei',
    'nav.coach': 'Coach',
    'nav.signIn': 'Inloggen',
    'nav.signOut': 'Uitloggen',
    
    // Language
    'language.english': 'Engels',
    'language.dutch': 'Nederlands',
    
    // Auth
    'auth.email': 'E-mail',
    'auth.password': 'Wachtwoord',
    'auth.confirmPassword': 'Bevestig Wachtwoord',
    'auth.enterEmail': 'Voer je e-mail in',
    'auth.enterPassword': 'Voer je wachtwoord in',
    'auth.confirmPasswordPlaceholder': 'Bevestig je wachtwoord',
    'auth.createAccount': 'Account Aanmaken',
    'auth.welcomeBack': 'Welkom Terug',
    'auth.startJourney': 'Begin vandaag je zielreis',
    'auth.continueJourney': 'Ga verder met je reis van zelfontdekking',
    'auth.alreadyHaveAccount': 'Heb je al een account? Inloggen',
    'auth.needAccount': 'Heb je een account nodig? Aanmelden',
    'auth.signUpSuccess': 'Account aangemaakt! Controleer je e-mail om je account te verifiëren.',
    'auth.welcomeBackMessage': 'Welkom terug bij je zielreis!',
    'auth.signInFailed': 'Inloggen mislukt. Controleer je inloggegevens.',
    'auth.signUpFailed': 'Account aanmaken mislukt. Probeer opnieuw.',
    'auth.passwordsDontMatch': 'Wachtwoorden komen niet overeen',
    'auth.passwordTooShort': 'Wachtwoord moet minimaal 6 tekens bevatten',
    'auth.success': 'Succes',
    'coach.signInRequired': 'Log in om toegang te krijgen tot je persoonlijke AI coach en groeitools.',
    
    // Coach
    'coach.soulGuide': 'Zielgids',
    'coach.newConversation': 'Nieuw Gesprek',
    'newConversationStarted': 'Nieuw gesprek gestart met {{agent}}',
    
    // Index/Home Page
    'index.welcome': 'Welkom bij Je <br /><span class="text-soul-purple">Zielreis</span>',
    'index.subtitle': 'Ontdek je authentieke pad door gepersonaliseerde AI-begeleiding en spirituele groeitools.',
    'index.dreams': 'Dromen & Doelen',
    'index.dreamsDesc': 'Transformeer dromen naar realiteit',
    'index.growth': 'Spirituele Groei',
    'index.growthDesc': 'Innerlijke wijsheid & reflectie',
    'index.companion': 'AI Metgezel',
    'index.companionDesc': 'Gepersonaliseerde begeleiding & chat',
    'index.demo': 'Bekijk Persoonlijkheidsdemo',
    'index.startJourney': 'Start Je Reis',
    'index.chatWithCompanion': 'Chat met AI Metgezel',
    'index.welcomeBackReady': 'Welkom terug! Je zielmetgezel is klaar om je verder te begeleiden op je reis.',
    'index.createToGetStarted': 'Welkom! Laten we je persoonlijke blauwdruk maken om te beginnen aan je zielreis.',
    'index.readyExplore': 'Perfect! Je bent helemaal klaar. Laten we je groeitools verkennen en je reis voortzetten.',
    'index.backToHome': 'Terug naar Home',
    'index.getStarted': 'Begin Nu',
    'index.signIn': 'Inloggen',
    
    // Rotating subtitle messages
    'index.rotatingMessages': [
      'Vastzittend? SoulSync toont je de volgende juiste stap.',
      'Verloren in de ruis? Ontdek begeleiding die tot je ziel spreekt.',
      'Te veel nadenken over je pad? Stem af, handel en adem weer.',
      'Als niets werkt, heeft je ontwerp de sleutel.',
      'SoulSync beëindigt de cyclus van forceren wat niet past.',
      'Niet lui. Niet kapot. Gewoon niet op één lijn.',
      'Je bent niet achterop — je bent van koers. SoulSync zet je koers weer uit.',
      'Geen plannen meer die negeren wie je bent.',
      'Doelen zijn niet het probleem. Strategie die je ziel negeert wel.',
      'Als burnout wint, brengt SoulSync je terug in lijn met vreugde. Breek je droom af — niet je geest.',
      'Verander chaos in helderheid, één ziel-afgestemde taak tegelijk.',
      'Productiviteit die je bedrading eert.',
      'Van blauwdruk naar actie — één afgestemde stap tegelijk.',
      'Eindelijk: een takensysteem gebouwd voor je energie, niet ertegen.',
      'Je doelen, je ritme, jouw manier.',
      'Droom groot. Laat SoulSync dan je pad reverse-engineeren.',
      'Elke taak in harmonie met wie je bent.',
      'Helderheid. Strategie. Actie. Alles vanuit je innerlijke code.',
      'Ziel-geleide productiviteit — zodat je daadwerkelijk kunt doorzetten. SoulSync helpt als je moe bent van gissen.',
      'Als je vastloopt, heb je geen meer wilskracht nodig — meer afstemming.',
      'Voel je gekend. Maak vooruitgang.',
      'Echte groei begint met zelfbegrip.',
      'Het gaat er niet om meer te doen — het gaat erom wat goed voor je is te doen.'
    ],
    
    // Onboarding
    'onboarding.welcome': 'Welkom bij SoulSync',
    'onboarding.welcomeDesc': 'Ik ben je persoonlijke astrologiegids. Laat me je helpen je kosmische blauwdruk te ontdekken.',
    'onboarding.beginJourney': 'Begin Mijn Reis',
    'onboarding.step': 'Stap',
    'onboarding.of': 'van',
    'onboarding.whatsYourName': 'Wat is je naam?',
    'onboarding.fullName': 'Volledige Naam',
    'onboarding.fullNamePlaceholder': 'Voer je volledige naam in',
    'onboarding.preferredName': 'Gewenste Naam (optioneel)',
    'onboarding.preferredNamePlaceholder': 'Hoe wil je aangesproken worden?',
    'onboarding.whenWereBorn': 'Wanneer ben je geboren?',
    'onboarding.birthDate': 'Geboortedatum',
    'onboarding.day': 'Dag',
    'onboarding.month': 'Maand',
    'onboarding.year': 'Jaar',
    'onboarding.selectExactDate': 'Selecteer je exacte geboortedatum voor nauwkeurige berekeningen',
    'onboarding.whatTimeWereBorn': 'Hoe laat ben je geboren?',
    'onboarding.birthTime': 'Geboortetime (Lokale Tijd)',
    'onboarding.birthTimeDesc': 'Voer de lokale tijd in waar je geboren bent - we regelen automatisch de tijdzone conversie',
    'onboarding.whereWereBorn': 'Waar ben je geboren?',
    'onboarding.birthLocation': 'Geboorteplaats',
    'onboarding.birthLocationPlaceholder': 'Stad, Land (bijv. Paramaribo, Suriname)',
    'onboarding.birthLocationDesc': 'We vinden automatisch de exacte coördinaten en historische tijdzone',
    'onboarding.tellPersonality': 'Vertel ons over je persoonlijkheid',
    'onboarding.generatingBlueprint': 'Je Ziel Blauwdruk Genereren',
    'onboarding.choosePath': 'Kies Je Pad',
    'onboarding.choosePathDesc': 'Laten we je coaching voorkeuren instellen om je ervaring te personaliseren.',
    'onboarding.authRequired': 'Authenticatie Vereist',
    'onboarding.authRequiredDesc': 'Log in om je Ziel Blauwdruk te genereren.',
    'onboarding.devMode': 'Dev Modus: Meerdere onboarding pogingen ondersteund',
    'onboarding.devModePrefs': 'Dev Modus: Voorkeuren worden opgeslagen in goal_stack',
    
    // Blueprint Generation
    'blueprint.generating': 'Je Ziel Blauwdruk genereren...',
    'blueprint.connecting': 'Verbinden met hemellichamen database...',
    'blueprint.calculating': 'Planetaire posities berekenen...',
    'blueprint.generatingProfile': 'Je unieke profiel genereren...',
    'blueprint.finalizing': 'Je Ziel Blauwdruk afronden...',
    'blueprint.complete': 'Blauwdruk Generatie Voltooid!',
    'blueprint.completeDesc': 'Je Ziel Blauwdruk is succesvol aangemaakt.',
    'blueprint.error': 'Blauwdruk Generatie Fout',
    'blueprint.tryAgain': 'Probeer Opnieuw',
    'blueprint.maxRetries': 'Maximum aantal pogingen bereikt. Controleer je informatie en probeer later opnieuw.',
    'blueprint.generated': 'Blauwdruk Succesvol Gegenereerd',
    'blueprint.generatedDesc': 'Je ziel blauwdruk is aangemaakt en klaar om te verkennen!',
    'blueprint.partial': 'Blauwdruk Generatie Gedeeltelijk',
    'blueprint.partialDesc': 'Sommige berekeningen waren niet volledig nauwkeurig, maar we hebben je blauwdruk gemaakt met de best beschikbare gegevens.',
    'blueprint.saveFailed': 'Je blauwdruk was gegenereerd maar kon niet worden opgeslagen. Probeer opnieuw.',
    'blueprint.unexpectedError': 'Er was een probleem met het genereren van je blauwdruk. Probeer opnieuw.',
    'blueprint.tooManyAttempts': 'Te Veel Pogingen',
    'blueprint.tooManyAttemptsDesc': 'Mislukt na {{attempts}} pogingen. Controleer je geboorte-informatie en probeer later opnieuw.',
    
    // Goal Selection
    'goals.primaryFocus': 'Wat is je primaire focusgebied?',
    'goals.guidanceLevel': 'Hoeveel begeleiding geef je de voorkeur?',
    'goals.lightTouch': 'Lichte aanraking',
    'goals.structuredGuidance': 'Gestructureerde begeleiding',
    'goals.yourSelections': 'Je Selecties:',
    'goals.focus': 'Focus:',
    'goals.guidanceLevelLabel': 'Begeleidingsniveau:',
    'goals.completeSetup': 'Installatie Voltooien',
    'goals.saving': 'Opslaan...',
    'goals.tryAgain': 'Probeer Opnieuw',
    'goals.exploring': 'Ik ben nog aan het verkennen en uitzoeken',
    'goals.personalGrowth': 'Persoonlijke Groei & Zelfontdekking',
    'goals.careerSuccess': 'Carrière Succes & Professionele Ontwikkeling',
    'goals.relationships': 'Relaties & Communicatie',
    'goals.healthWellness': 'Gezondheid & Welzijn',
    'goals.creativity': 'Creativiteit & Zelfexpressie',
    'goals.spiritualDevelopment': 'Spirituele Ontwikkeling',
    'goals.guidance1': 'Minimale begeleiding - Ik verkies zelf te verkennen',
    'goals.guidance2': 'Lichte begeleiding - Af en toe suggesties en inzichten',
    'goals.guidance3': 'Gebalanceerde aanpak - Regelmatige begeleiding met flexibiliteit',
    'goals.guidance4': 'Actieve begeleiding - Gestructureerde ondersteuning en aanbevelingen',
    'goals.guidance5': 'Maximale begeleiding - Uitgebreide coaching en richting',
    'goals.welcomeComplete': 'Welkom bij SoulSync!',
    'goals.welcomeCompleteDesc': 'Je Ziel Blauwdruk is compleet. Welkom bij je gepersonaliseerde reis.',
    'goals.errorSaving': 'Fout bij Opslaan Voorkeuren',
    
    // Growth
    'growth.title': 'Groei Modus',
    'growth.headerSubtitle': 'Innerlijke reflectie & zielwijsheid',
    'growth.positionLabel': 'Positie:',
    'growth.conversationMessages': 'gesprekberichten',
    'growth.chooseYourTool': 'Kies Je Zieltool',
    'growth.chooseYourToolDescription': 'Selecteer een van de tools hierboven om je innerlijke reis te beginnen.',
    'growth.startSoulCheckIn': 'Start Ziel Check-in',
    'growth.exploringArea': '{{area}} verkennen',
    
    // Growth Tools
    'growth.tools.soulGuide': 'Ziel Gids',
    'growth.tools.moodTracker': 'Stemmingsmeter',
    'growth.tools.reflectionPrompts': 'Reflectievragen',
    'growth.tools.insightJournal': 'Inzichtenjournal',
    'growth.tools.weeklyInsights': 'Wekelijkse Inzichten',
    'growth.tools.freeChat': 'Vrije Chat',
    
    // Life Areas
    'lifeArea.selector.title': 'Kies Je Levensgebied',
    'lifeArea.selector.subtitle': 'Selecteer een levensgebied om te verkennen en te groeien',
    'lifeArea.home.name': 'Thuis',
    'lifeArea.home.description': 'Familie, woonruimte, huiselijke harmonie',
    'lifeArea.career.name': 'Carrière',
    'lifeArea.career.description': 'Doel, professionele groei, impact',
    'lifeArea.finances.name': 'Financiën',
    'lifeArea.finances.description': 'Abundance, zekerheid, geld mindset',
    'lifeArea.relationships.name': 'Relaties',
    'lifeArea.relationships.description': 'Liefde, vriendschap, gemeenschapsverbinding',
    'lifeArea.wellbeing.name': 'Welzijn',
    'lifeArea.wellbeing.description': 'Gezondheid, energie, mentale helderheid',
    'lifeArea.creativity.name': 'Creativiteit',
    'lifeArea.creativity.description': 'Artistieke expressie, innovatie, verbeelding',
    'lifeArea.spirituality.name': 'Spiritualiteit',
    'lifeArea.spirituality.description': 'Zielverbinding, innerlijke wijsheid, heilige praktijken',
    
    // Dreams
    'dreams.title': 'Dromen & Doelen',
    'dreams.description': 'Transformeer je dromen in haalbare reizen met AI-begeleiding.',
    'dreams.getStarted': 'Begin Nu',
    'dreams.whatsYourDream': 'Wat is Je Droom?',
    'dreams.heroDescription': 'Transformeer je grootste dromen in een gepersonaliseerde reis met AI-aangedreven mijlpalen en ziel-afgestemde begeleiding.',
    'dreams.placeholderDream': 'Ik wil mijn eigen bedrijf starten...',
    'dreams.whyImportant': 'Waarom is dit belangrijk voor je?',
    'dreams.placeholderWhy': 'Dit geeft me vrijheid en doel...',
    'dreams.category': 'Categorie',
    'dreams.timeline': 'Tijdlijn',
    'dreams.createJourney': 'Creëer Mijn Reis',
    'dreams.creatingJourney': 'Je reis wordt gecreëerd...',
    'dreams.aiInsighLabel': 'Of laat AI je begeleiden:',
    'dreams.aiButtonTitle': 'AI-Begeleide Droomontdekking',
    'dreams.aiButtonDesc': 'Laat me je helpen je dromen te ontdekken en definiëren',
    'dreams.journeyButtonTitle': 'Bekijk Bestaande Reis',
    'dreams.journeyButtonDesc': 'Ga verder met je huidige droomreis',
    'dreams.yourJourney': 'Je Reis',
    'dreams.trackProgress': 'Volg je voortgang en mijlpalen',
    'dreams.newDream': 'Nieuwe Droom',
    'dreams.new': 'Nieuw',
    'dreams.tabs.journey': 'Reis',
    'dreams.tabs.tasks': 'Taken',
    'dreams.tabs.focus': 'Focus',
    'dreams.tabs.habits': 'Gewoonten',
    'dreams.tab.yourTasks': 'Je Taken',
    'dreams.tab.focusSession': 'Focus Sessie',
    'dreams.tab.habits': 'Dagelijkse Gewoonten',
    
    // Goals
    'goals.categoryPersonal': 'Persoonlijke Groei',
    'goals.categoryCareer': 'Carrière & Doel',
    'goals.categoryHealth': 'Gezondheid & Welzijn',
    'goals.categoryRelationships': 'Relaties',
    'goals.categoryCreative': 'Creativiteit & Expressie',
    'goals.categoryFinancial': 'Financieel',
    'goals.categorySpiritual': 'Spiritueel',
    'goals.targetDate': 'Doeldatum',
    
    // Mood Tracker
    'mood.title': 'Dagelijkse Stemming & Energie Check-in',
    'mood.subtitle': 'Volg je emotionele patronen en energieniveaus',
    'mood.currentMood': 'Hoe voel je je nu?',
    'mood.energyLevel': 'Hoe is je energie?',
    'mood.saveEntry': 'Stemming Opslaan',
    'mood.entrySaved': 'Stemming opgeslagen!',
    'mood.entryDescription': 'Je stemmingspatronen helpen emotionele trends en triggers te identificeren.',
    'mood.moods.joyful': 'Vreugdevol',
    'mood.moods.peaceful': 'Vredig',
    'mood.moods.grateful': 'Dankbaar',
    'mood.moods.excited': 'Opgewonden',
    'mood.moods.neutral': 'Neutraal',
    'mood.moods.tired': 'Moe',
    'mood.moods.anxious': 'Angstig',
    'mood.moods.frustrated': 'Gefrustreerd',
    'mood.moods.sad': 'Verdrietig',
    'mood.energy.high': 'Hoge Energie',
    'mood.energy.steady': 'Stabiele Energie',
    'mood.energy.low': 'Lage Energie',
    'mood.energy.depleted': 'Uitgeput',
    
    // MoodTracker specific
    'moodTracker.title': 'Dagelijkse Stemming & Energie Check-in',
    'moodTracker.emotionalState': 'Hoe voel je je nu?',
    'moodTracker.energyLevel': 'Hoe is je energie?',
    'moodTracker.joyful': 'Vreugdevol',
    'moodTracker.content': 'Tevreden',
    'moodTracker.neutral': 'Neutraal',
    'moodTracker.reflective': 'Nadenkend',
    'moodTracker.challenged': 'Uitgedaagd',
    'moodTracker.high': 'Hoge Energie',
    'moodTracker.steady': 'Stabiele Energie',
    'moodTracker.low': 'Lage Energie',
    'moodTracker.moodTracked': 'Stemming bijgehouden',
    'moodTracker.moodSaved': 'stemming met {{energy}} energie opgeslagen',
    'moodTracker.saveToPatterns': 'Opslaan in Patronen',
    'moodTracker.patternsHelp': 'Je stemmingspatronen helpen emotionele trends en triggers te identificeren.',
    
    // Guide Interface
    'guide.innerCompass': 'Innerlijk Kompas',
    'guide.reflectionMode': 'Reflectie Modus',
    'guide.checkIn': 'Check In',
    'guide.reflect': 'Reflecteren',
    'guide.journal': 'Journaal',
    'guide.description': 'Je persoonlijke toolkit voor diepe zielverkenning en authentieke groei.',
    'guide.awaits': 'Je Zielgids Wacht',
    'guide.awaitsDescription': 'Deel wat er in je hart leeft, en laten we samen je innerlijke wijsheid verkennen.',
    'guide.reflecting': 'Reflecteren op je zielwijsheid...',
    'guide.inputPlaceholder': 'Deel wat er in je hart leeft...',
    'guide.poweredBy': 'Aangedreven door zielwijsheid & authentieke begeleiding',
    'guide.exploreDeeper': 'Dieper Verkennen',
    'guide.blueprintLink': 'Blauwdruk Link',
    'guide.tellMore': 'Vertel me meer over dit inzicht en hoe het verbonden is met mijn persoonlijke groei.',
    'guide.howConnect': 'Hoe verbindt dit met mijn blauwdruk en authentieke zelf?',
    
    // Insight Journal
    'journal.title': 'Ziel Inzichten Journaal',
    'journal.placeholder': 'Leg je inzichten, realisaties of aha-momenten vast...',
    'journal.tagLabel': 'Label dit inzicht:',
    'journal.saveButton': 'Opslaan in Journaal',
    'journal.saved': 'Inzicht opgeslagen in je journaal!',
    'journal.description': 'Je inzichten creëren een persoonlijke kennisbank voor patroonherkenning en groeivolging.',
    'journal.tags.breakthrough': 'Doorbraak',
    'journal.tags.pattern': 'Patroon',
    'journal.tags.gratitude': 'Dankbaarheid',
    'journal.tags.challenge': 'Uitdaging',
    'journal.tags.growth': 'Groei',
    'journal.tags.clarity': 'Helderheid',
    'journal.tags.alignment': 'Afstemming',
    'journal.tags.wisdom': 'Wijsheid',
    
    // Weekly Insights
    'weekly.title': 'Je Wekelijkse Ziel Inzichten',
    'weekly.growthScore': 'Groei Score',
    'weekly.dominantMood': 'Dominante Stemmingspatroon',
    'weekly.keyReflections': 'Belangrijke Reflectiegebieden',
    'weekly.growthThemes': 'Groei Thema\'s',
    'weekly.observedPatterns': 'Waargenomen Patronen',
    'weekly.patterns.awareness': 'Zelfbewustzijn neemt toe',
    'weekly.patterns.consistency': 'Consistentie opbouwen',
    
    // Reflection Prompts
    'reflection.title': 'Reflectie & Groei Volgen',
    'reflection.dailyReflection': 'Dagelijkse Reflectie',
    'reflection.deepInsight': 'Diep Inzicht',
    'reflection.lifeDirection': 'Levensrichting',
    'reflection.saveReflection': 'Reflectie Opslaan',
    'reflection.saved': 'Reflectie opgeslagen in je groeipatronen!',
    'reflection.description': 'Je reflecties bouwen een persoonlijke groeidatabase voor wekelijkse inzichten en patroonherkenning.',
    'reflection.placeholder': 'Schrijf hier je gedachten en inzichten...',
    'reflection.reflecting': 'Reflecteren op:',
    
    // Daily Reflection Prompts
    'reflection.daily.joy': 'Wat bracht me vandaag het meeste vreugde?',
    'reflection.daily.challenge': 'Wat daagde me uit en wat heb ik geleerd?',
    'reflection.daily.authentic': 'Hoe heb ik vandaag mijn authentieke zelf geëerd?',
    'reflection.daily.gratitude': 'Waar ben ik nu dankbaar voor?',
    
    // Deep Insight Prompts
    'reflection.insight.pattern': 'Welk patroon blijft terugkomen in mijn leven?',
    'reflection.insight.soul': 'Wat probeert mijn ziel me te vertellen?',
    'reflection.insight.comfort': 'Hoe groei ik voorbij mijn comfortzone?',
    'reflection.insight.blueprint': 'Wat onthult mijn blauwdruk over deze situatie?',
    
    // Life Direction Prompts
    'reflection.direction.aligned': 'Wat voelt het meest afgestemd op mijn doel?',
    'reflection.direction.resisting': 'Waar verzet ik me tegen mijn natuurlijke stroom?',
    'reflection.direction.trust': 'Wat zou ik doen als ik mezelf volledig vertrouwde?',
    'reflection.direction.energy': 'Hoe kan ik vandaag mijn authentieke energie eren?',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, params?: Record<string, string>): string => {
    console.log(`[i18n] language: ${language}, key: ${key}, translation: ${translations[language][key] || key}`);
    
    let translation = translations[language][key] || translations['en'][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{{${paramKey}}}`, paramValue);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
